tasks:
  0:
    loss_weight: 1.0
    gres_ratio: 1
    task_name: DataBuilder_ctcc
    # ceph or cluster
    root_path: <your project root> + Instruct-ReID/data/real1
    train_file_path: <your project root> + Instruct-ReID/data/real1/datalist/train_ctcc.txt