tasks:
  0:
    loss_weight: 1.0
    gres_ratio: 1
    task_name: DataBuilder_t2i
    attt_file: <your project root> + Instruct-ReID/data/cuhk_pedes/caption_t2i_v2.json
    root_path: <your project root> + Instruct-ReID/data/cuhk_pedes
    train_file_path: <your project root> + Instruct-ReID/data/cuhk_pedes/train_t2i_v2.txt